version: '3.8'

services:
  # Database
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: satellite_telemetry
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d satellite_telemetry"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend API
  api:
    image: brandonhargitay/turion-take-home-api:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://admin:password@postgres:5432/satellite_telemetry"
    depends_on:
      postgres:
        condition: service_healthy

  # Frontend
  frontend:
    image: brandonhargitay/turion-take-home-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api

  # Telemetry Generator
  telemetry:
    image: brandonhargitay/turion-take-home-telemetry:latest
    build:
      context: .
      dockerfile: telemetry.Dockerfile
    depends_on:
      - api

volumes:
  postgres_data: 